version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: docker/php-fpm
    expose:
      - 9000
    volumes:
      - .:/var/www/app
    env_file:
      - ./.env.local
    depends_on:
      - database

  database:
    build:
      context: docker/database
    env_file:
      - ./.env.local
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql
