version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    # image: php:fpm-alpine
    build:
      context: docker/php-fpm
    expose:
      - 9000
    volumes:
      - .:/var/www/app
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=mariadb-10.5.5
    depends_on:
      - database

  database:
    build:
      context: docker/database
    env_file:
      - ./.env
    environment:
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql
