services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\Tests\Behat\ShopContext:
      public: true
      arguments:
        - "@kernel"
        - "@doctrine.orm.entity_manager"
        - "@app.repository.record"
